CREATE TABLE IF NOT EXISTS projects (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    owner_user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(160) NOT NULL UNIQUE,
    description VARCHAR(2000) NOT NULL DEFAULT '',
    status ENUM('active','archived') NOT NULL DEFAULT 'active',
    default_interval_seconds INT NOT NULL DEFAULT 300,
    default_timeout_ms INT NOT NULL DEFAULT 5000,
    default_retries INT NOT NULL DEFAULT 1,
    failure_threshold INT NOT NULL DEFAULT 3,
    recovery_success_threshold INT NOT NULL DEFAULT 1,
    routes_total INT NOT NULL DEFAULT 0,
    routes_healthy INT NOT NULL DEFAULT 0,
    routes_degraded INT NOT NULL DEFAULT 0,
    routes_failing INT NOT NULL DEFAULT 0,
    routes_disabled INT NOT NULL DEFAULT 0,
    routes_unknown INT NOT NULL DEFAULT 0,
    uptime_24h_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
    avg_latency_24h_ms INT NOT NULL DEFAULT 0,
    checks_24h INT NOT NULL DEFAULT 0,
    failures_24h INT NOT NULL DEFAULT 0,
    open_incidents INT NOT NULL DEFAULT 0,
    last_check_at DATETIME NULL,
    metrics_updated_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_projects_owner (owner_user_id),
    INDEX idx_projects_status (status),
    FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS project_members (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role ENUM('owner','editor','viewer') NOT NULL DEFAULT 'viewer',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_project_member (project_id, user_id),
    INDEX idx_project_members_user (user_id),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS api_routes (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    method ENUM('GET','POST','PUT','PATCH','DELETE','HEAD','OPTIONS','TRACE') NOT NULL,
    path VARCHAR(1024) NOT NULL,
    base_url VARCHAR(2083) NOT NULL DEFAULT '',
    operation_id VARCHAR(255) NOT NULL DEFAULT '',
    name VARCHAR(255) NOT NULL DEFAULT '',
    summary VARCHAR(1024) NOT NULL DEFAULT '',
    description TEXT NULL,
    tags JSON NULL,
    deprecated TINYINT(1) NOT NULL DEFAULT 0,
    parameters JSON NULL,
    request_body JSON NULL,
    responses JSON NULL,
    security JSON NULL,
    headers JSON NULL,
    spec_hash CHAR(64) NOT NULL DEFAULT '',
    source ENUM('manual','import') NOT NULL DEFAULT 'manual',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    monitor_interval_seconds INT NOT NULL DEFAULT 300,
    timeout_ms INT NOT NULL DEFAULT 5000,
    retries INT NOT NULL DEFAULT 1,
    expected_status_range VARCHAR(255) NOT NULL DEFAULT '200-399',
    failure_threshold INT NOT NULL DEFAULT 3,
    recovery_successes INT NOT NULL DEFAULT 1,
    status ENUM('healthy','degraded','failing','disabled','unknown') NOT NULL DEFAULT 'unknown',
    last_checked_at DATETIME NULL,
    last_status_code INT NOT NULL DEFAULT 0,
    last_latency_ms INT NOT NULL DEFAULT 0,
    last_failure_reason VARCHAR(1024) NULL,
    consecutive_failures INT NOT NULL DEFAULT 0,
    consecutive_successes INT NOT NULL DEFAULT 0,
    next_check_at DATETIME NOT NULL,
    uptime_24h_pct DECIMAL(5,2) NOT NULL DEFAULT 0,
    avg_latency_24h_ms INT NOT NULL DEFAULT 0,
    checks_24h INT NOT NULL DEFAULT 0,
    failures_24h INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    -- Prefix-indexed for the same reason as websites.url above: project_id (8)
    -- + method (1) + path(700) * 4 bytes = 2809 bytes, inside InnoDB's
    -- 3072-byte key limit under utf8mb4. A full VARCHAR(1024) column would
    -- need 4105 bytes and the CREATE would fail.
    UNIQUE KEY uq_route_method_path (project_id, method, path(700)),
    INDEX idx_routes_project_status (project_id, status),
    INDEX idx_routes_project_enabled (project_id, enabled),
    INDEX idx_routes_next_check_at (next_check_at),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS route_checks (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    route_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    status ENUM('up','down') NOT NULL,
    status_code INT NOT NULL DEFAULT 0,
    latency_ms INT NOT NULL DEFAULT 0,
    failure_reason VARCHAR(1024) NULL,
    attempt INT NOT NULL DEFAULT 1,
    checked_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_route_checks_route_checked_at (route_id, checked_at DESC),
    INDEX idx_route_checks_project_checked_at (project_id, checked_at DESC),
    FOREIGN KEY (route_id) REFERENCES api_routes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS route_incidents (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    route_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    state ENUM('open','resolved') NOT NULL DEFAULT 'open',
    started_at DATETIME NOT NULL,
    resolved_at DATETIME NULL,
    failure_count INT NOT NULL DEFAULT 0,
    last_failure_reason VARCHAR(1024) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_route_incidents_route_state (route_id, state),
    INDEX idx_route_incidents_project_state (project_id, state),
    FOREIGN KEY (route_id) REFERENCES api_routes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS route_import_jobs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    project_id BIGINT NOT NULL,
    created_by_user_id BIGINT NOT NULL,
    source_type ENUM('file','paste') NOT NULL,
    spec_format ENUM('openapi3','swagger2') NOT NULL,
    status ENUM('validated','committed','failed') NOT NULL DEFAULT 'validated',
    parsed_items LONGTEXT NULL,
    total_parsed INT NOT NULL DEFAULT 0,
    created_routes INT NOT NULL DEFAULT 0,
    updated_routes INT NOT NULL DEFAULT 0,
    skipped_routes INT NOT NULL DEFAULT 0,
    removed_routes INT NOT NULL DEFAULT 0,
    error_message VARCHAR(2000) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_import_jobs_project (project_id, created_at DESC),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE CASCADE
);
